// Generated by gencpp from file raspberry_msgs/Acc.msg
// DO NOT EDIT!


#ifndef RASPBERRY_MSGS_MESSAGE_ACC_H
#define RASPBERRY_MSGS_MESSAGE_ACC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspberry_msgs
{
template <class ContainerAllocator>
struct Acc_
{
  typedef Acc_<ContainerAllocator> Type;

  Acc_()
    : a_x(0.0)
    , a_y(0.0)
    , a_z(0.0)
    , time(0)  {
    }
  Acc_(const ContainerAllocator& _alloc)
    : a_x(0.0)
    , a_y(0.0)
    , a_z(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef float _a_x_type;
  _a_x_type a_x;

   typedef float _a_y_type;
  _a_y_type a_y;

   typedef float _a_z_type;
  _a_z_type a_z;

   typedef int64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::raspberry_msgs::Acc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspberry_msgs::Acc_<ContainerAllocator> const> ConstPtr;

}; // struct Acc_

typedef ::raspberry_msgs::Acc_<std::allocator<void> > Acc;

typedef boost::shared_ptr< ::raspberry_msgs::Acc > AccPtr;
typedef boost::shared_ptr< ::raspberry_msgs::Acc const> AccConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspberry_msgs::Acc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspberry_msgs::Acc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspberry_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'raspberry_msgs': ['/home/pi/Documents/robomagellan/Codigos/Raspberry/ROS/catkin_BUZZ/src/raspberry_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Acc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Acc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Acc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Acc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Acc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Acc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspberry_msgs::Acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79dbd4567e140183ab42121735f0a17c";
  }

  static const char* value(const ::raspberry_msgs::Acc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79dbd4567e140183ULL;
  static const uint64_t static_value2 = 0xab42121735f0a17cULL;
};

template<class ContainerAllocator>
struct DataType< ::raspberry_msgs::Acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspberry_msgs/Acc";
  }

  static const char* value(const ::raspberry_msgs::Acc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspberry_msgs::Acc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a_x\n\
float32 a_y\n\
float32 a_z\n\
int64 time\n\
";
  }

  static const char* value(const ::raspberry_msgs::Acc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspberry_msgs::Acc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a_x);
      stream.next(m.a_y);
      stream.next(m.a_z);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Acc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspberry_msgs::Acc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspberry_msgs::Acc_<ContainerAllocator>& v)
  {
    s << indent << "a_x: ";
    Printer<float>::stream(s, indent + "  ", v.a_x);
    s << indent << "a_y: ";
    Printer<float>::stream(s, indent + "  ", v.a_y);
    s << indent << "a_z: ";
    Printer<float>::stream(s, indent + "  ", v.a_z);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPBERRY_MSGS_MESSAGE_ACC_H
