// Generated by gencpp from file raspberry_msgs/GPS.msg
// DO NOT EDIT!


#ifndef RASPBERRY_MSGS_MESSAGE_GPS_H
#define RASPBERRY_MSGS_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspberry_msgs
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : valid(false)
    , lat(0.0)
    , lng(0.0)
    , alt(0.0)
    , speed(0.0)
    , course(0.0)
    , hdop(0.0)
    , vdop(0.0)
    , pdop(0.0)
    , time(0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : valid(false)
    , lat(0.0)
    , lng(0.0)
    , alt(0.0)
    , speed(0.0)
    , course(0.0)
    , hdop(0.0)
    , vdop(0.0)
    , pdop(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lng_type;
  _lng_type lng;

   typedef double _alt_type;
  _alt_type alt;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _course_type;
  _course_type course;

   typedef float _hdop_type;
  _hdop_type hdop;

   typedef float _vdop_type;
  _vdop_type vdop;

   typedef float _pdop_type;
  _pdop_type pdop;

   typedef int64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::raspberry_msgs::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspberry_msgs::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::raspberry_msgs::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::raspberry_msgs::GPS > GPSPtr;
typedef boost::shared_ptr< ::raspberry_msgs::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspberry_msgs::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspberry_msgs::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspberry_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'raspberry_msgs': ['/home/pi/Documents/robomagellan/Codigos/Raspberry/ROS/catkin_BUZZ/src/raspberry_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspberry_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71546074f6ec76fd1ffdf15346a8ac4a";
  }

  static const char* value(const ::raspberry_msgs::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71546074f6ec76fdULL;
  static const uint64_t static_value2 = 0x1ffdf15346a8ac4aULL;
};

template<class ContainerAllocator>
struct DataType< ::raspberry_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspberry_msgs/GPS";
  }

  static const char* value(const ::raspberry_msgs::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspberry_msgs::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid\n\
float64 lat\n\
float64 lng\n\
float64 alt\n\
float64 speed\n\
float64 course\n\
float32 hdop\n\
float32 vdop\n\
float32 pdop\n\
int64 time\n\
";
  }

  static const char* value(const ::raspberry_msgs::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspberry_msgs::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
      stream.next(m.lat);
      stream.next(m.lng);
      stream.next(m.alt);
      stream.next(m.speed);
      stream.next(m.course);
      stream.next(m.hdop);
      stream.next(m.vdop);
      stream.next(m.pdop);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspberry_msgs::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspberry_msgs::GPS_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lng: ";
    Printer<double>::stream(s, indent + "  ", v.lng);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "course: ";
    Printer<double>::stream(s, indent + "  ", v.course);
    s << indent << "hdop: ";
    Printer<float>::stream(s, indent + "  ", v.hdop);
    s << indent << "vdop: ";
    Printer<float>::stream(s, indent + "  ", v.vdop);
    s << indent << "pdop: ";
    Printer<float>::stream(s, indent + "  ", v.pdop);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPBERRY_MSGS_MESSAGE_GPS_H
