// Generated by gencpp from file raspberry_msgs/Gyro.msg
// DO NOT EDIT!


#ifndef RASPBERRY_MSGS_MESSAGE_GYRO_H
#define RASPBERRY_MSGS_MESSAGE_GYRO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspberry_msgs
{
template <class ContainerAllocator>
struct Gyro_
{
  typedef Gyro_<ContainerAllocator> Type;

  Gyro_()
    : g_x(0.0)
    , g_y(0.0)
    , g_z(0.0)
    , time(0)  {
    }
  Gyro_(const ContainerAllocator& _alloc)
    : g_x(0.0)
    , g_y(0.0)
    , g_z(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef float _g_x_type;
  _g_x_type g_x;

   typedef float _g_y_type;
  _g_y_type g_y;

   typedef float _g_z_type;
  _g_z_type g_z;

   typedef int64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::raspberry_msgs::Gyro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspberry_msgs::Gyro_<ContainerAllocator> const> ConstPtr;

}; // struct Gyro_

typedef ::raspberry_msgs::Gyro_<std::allocator<void> > Gyro;

typedef boost::shared_ptr< ::raspberry_msgs::Gyro > GyroPtr;
typedef boost::shared_ptr< ::raspberry_msgs::Gyro const> GyroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspberry_msgs::Gyro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspberry_msgs::Gyro_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspberry_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'raspberry_msgs': ['/home/pi/Documents/robomagellan/Codigos/Raspberry/ROS/catkin_BUZZ/src/raspberry_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Gyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Gyro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Gyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Gyro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Gyro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Gyro_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspberry_msgs::Gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdbe35c96cc4518a9444f2526afab160";
  }

  static const char* value(const ::raspberry_msgs::Gyro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdbe35c96cc4518aULL;
  static const uint64_t static_value2 = 0x9444f2526afab160ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspberry_msgs::Gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspberry_msgs/Gyro";
  }

  static const char* value(const ::raspberry_msgs::Gyro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspberry_msgs::Gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 g_x\n\
float32 g_y\n\
float32 g_z\n\
int64 time\n\
";
  }

  static const char* value(const ::raspberry_msgs::Gyro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspberry_msgs::Gyro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.g_x);
      stream.next(m.g_y);
      stream.next(m.g_z);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gyro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspberry_msgs::Gyro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspberry_msgs::Gyro_<ContainerAllocator>& v)
  {
    s << indent << "g_x: ";
    Printer<float>::stream(s, indent + "  ", v.g_x);
    s << indent << "g_y: ";
    Printer<float>::stream(s, indent + "  ", v.g_y);
    s << indent << "g_z: ";
    Printer<float>::stream(s, indent + "  ", v.g_z);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPBERRY_MSGS_MESSAGE_GYRO_H
