// Generated by gencpp from file raspberry_msgs/Mag.msg
// DO NOT EDIT!


#ifndef RASPBERRY_MSGS_MESSAGE_MAG_H
#define RASPBERRY_MSGS_MESSAGE_MAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspberry_msgs
{
template <class ContainerAllocator>
struct Mag_
{
  typedef Mag_<ContainerAllocator> Type;

  Mag_()
    : m_x(0.0)
    , m_y(0.0)
    , m_z(0.0)
    , tempo(0)  {
    }
  Mag_(const ContainerAllocator& _alloc)
    : m_x(0.0)
    , m_y(0.0)
    , m_z(0.0)
    , tempo(0)  {
  (void)_alloc;
    }



   typedef double _m_x_type;
  _m_x_type m_x;

   typedef double _m_y_type;
  _m_y_type m_y;

   typedef double _m_z_type;
  _m_z_type m_z;

   typedef int64_t _tempo_type;
  _tempo_type tempo;




  typedef boost::shared_ptr< ::raspberry_msgs::Mag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspberry_msgs::Mag_<ContainerAllocator> const> ConstPtr;

}; // struct Mag_

typedef ::raspberry_msgs::Mag_<std::allocator<void> > Mag;

typedef boost::shared_ptr< ::raspberry_msgs::Mag > MagPtr;
typedef boost::shared_ptr< ::raspberry_msgs::Mag const> MagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspberry_msgs::Mag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspberry_msgs::Mag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace raspberry_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'raspberry_msgs': ['/home/pi/Documents/robomagellan/Codigos/Raspberry/ROS/catkin_BUZZ/src/raspberry_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Mag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry_msgs::Mag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Mag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry_msgs::Mag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Mag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry_msgs::Mag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspberry_msgs::Mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0462b2824ebe44c25937b0cc174267f0";
  }

  static const char* value(const ::raspberry_msgs::Mag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0462b2824ebe44c2ULL;
  static const uint64_t static_value2 = 0x5937b0cc174267f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspberry_msgs::Mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspberry_msgs/Mag";
  }

  static const char* value(const ::raspberry_msgs::Mag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspberry_msgs::Mag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 m_x\n\
float64 m_y\n\
float64 m_z\n\
int64 tempo\n\
";
  }

  static const char* value(const ::raspberry_msgs::Mag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspberry_msgs::Mag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m_x);
      stream.next(m.m_y);
      stream.next(m.m_z);
      stream.next(m.tempo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspberry_msgs::Mag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspberry_msgs::Mag_<ContainerAllocator>& v)
  {
    s << indent << "m_x: ";
    Printer<double>::stream(s, indent + "  ", v.m_x);
    s << indent << "m_y: ";
    Printer<double>::stream(s, indent + "  ", v.m_y);
    s << indent << "m_z: ";
    Printer<double>::stream(s, indent + "  ", v.m_z);
    s << indent << "tempo: ";
    Printer<int64_t>::stream(s, indent + "  ", v.tempo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPBERRY_MSGS_MESSAGE_MAG_H
