# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raspberry_msgs/GPS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GPS(genpy.Message):
  _md5sum = "5d82aab34ae4b4ded06df8be5cebce30"
  _type = "raspberry_msgs/GPS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool valid
float64 lat
float64 lng
float64 alt
float64 speed
float32 hdop
float32 vdop
float32 pdop
int64 time"""
  __slots__ = ['valid','lat','lng','alt','speed','hdop','vdop','pdop','time']
  _slot_types = ['bool','float64','float64','float64','float64','float32','float32','float32','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       valid,lat,lng,alt,speed,hdop,vdop,pdop,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GPS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.valid is None:
        self.valid = False
      if self.lat is None:
        self.lat = 0.
      if self.lng is None:
        self.lng = 0.
      if self.alt is None:
        self.alt = 0.
      if self.speed is None:
        self.speed = 0.
      if self.hdop is None:
        self.hdop = 0.
      if self.vdop is None:
        self.vdop = 0.
      if self.pdop is None:
        self.pdop = 0.
      if self.time is None:
        self.time = 0
    else:
      self.valid = False
      self.lat = 0.
      self.lng = 0.
      self.alt = 0.
      self.speed = 0.
      self.hdop = 0.
      self.vdop = 0.
      self.pdop = 0.
      self.time = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4d3fq.pack(_x.valid, _x.lat, _x.lng, _x.alt, _x.speed, _x.hdop, _x.vdop, _x.pdop, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 53
      (_x.valid, _x.lat, _x.lng, _x.alt, _x.speed, _x.hdop, _x.vdop, _x.pdop, _x.time,) = _struct_B4d3fq.unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4d3fq.pack(_x.valid, _x.lat, _x.lng, _x.alt, _x.speed, _x.hdop, _x.vdop, _x.pdop, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 53
      (_x.valid, _x.lat, _x.lng, _x.alt, _x.speed, _x.hdop, _x.vdop, _x.pdop, _x.time,) = _struct_B4d3fq.unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4d3fq = struct.Struct("<B4d3fq")
