// Generated by gencpp from file bruce_vision/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BRUCE_VISION_MESSAGE_ADDTWOINTS_H
#define BRUCE_VISION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <bruce_vision/AddTwoIntsRequest.h>
#include <bruce_vision/AddTwoIntsResponse.h>


namespace bruce_vision
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace bruce_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bruce_vision::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::bruce_vision::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::bruce_vision::AddTwoInts > {
  static const char* value()
  {
    return "bruce_vision/AddTwoInts";
  }

  static const char* value(const ::bruce_vision::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::bruce_vision::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::bruce_vision::AddTwoInts > 
template<>
struct MD5Sum< ::bruce_vision::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_vision::AddTwoInts >::value();
  }
  static const char* value(const ::bruce_vision::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_vision::AddTwoIntsRequest> should match 
// service_traits::DataType< ::bruce_vision::AddTwoInts > 
template<>
struct DataType< ::bruce_vision::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::bruce_vision::AddTwoInts >::value();
  }
  static const char* value(const ::bruce_vision::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bruce_vision::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::bruce_vision::AddTwoInts > 
template<>
struct MD5Sum< ::bruce_vision::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_vision::AddTwoInts >::value();
  }
  static const char* value(const ::bruce_vision::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_vision::AddTwoIntsResponse> should match 
// service_traits::DataType< ::bruce_vision::AddTwoInts > 
template<>
struct DataType< ::bruce_vision::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::bruce_vision::AddTwoInts >::value();
  }
  static const char* value(const ::bruce_vision::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRUCE_VISION_MESSAGE_ADDTWOINTS_H
