(cl:defpackage arduino_msgs-msg
  (:use )
  (:export
   "<STAMPEDUINT32>"
   "STAMPEDUINT32"
   "<STAMPEDCHAR>"
   "STAMPEDCHAR"
   "<STAMPEDSTRING>"
   "STAMPEDSTRING"
   "<STAMPEDINT64>"
   "STAMPEDINT64"
   "<STAMPEDINT32>"
   "STAMPEDINT32"
   "<STAMPEDUINT8>"
   "STAMPEDUINT8"
   "<STAMPEDBOOL>"
   "STAMPEDBOOL"
   "<STAMPEDUINT64>"
   "STAMPEDUINT64"
   "<STAMPEDINT8>"
   "STAMPEDINT8"
   "<STAMPEDFLOAT32>"
   "STAMPEDFLOAT32"
   "<STAMPEDFLOAT64>"
   "STAMPEDFLOAT64"
  ))

