// Generated by gencpp from file robo_virtual/Posicao.msg
// DO NOT EDIT!


#ifndef ROBO_VIRTUAL_MESSAGE_POSICAO_H
#define ROBO_VIRTUAL_MESSAGE_POSICAO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_virtual
{
template <class ContainerAllocator>
struct Posicao_
{
  typedef Posicao_<ContainerAllocator> Type;

  Posicao_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , velocidade(0.0)  {
    }
  Posicao_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , velocidade(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _velocidade_type;
  _velocidade_type velocidade;




  typedef boost::shared_ptr< ::robo_virtual::Posicao_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_virtual::Posicao_<ContainerAllocator> const> ConstPtr;

}; // struct Posicao_

typedef ::robo_virtual::Posicao_<std::allocator<void> > Posicao;

typedef boost::shared_ptr< ::robo_virtual::Posicao > PosicaoPtr;
typedef boost::shared_ptr< ::robo_virtual::Posicao const> PosicaoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_virtual::Posicao_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_virtual::Posicao_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_virtual

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robo_virtual': ['/home/leticia/catkin_Leticia/src/robo_virtual/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_virtual::Posicao_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_virtual::Posicao_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_virtual::Posicao_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_virtual::Posicao_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_virtual::Posicao_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_virtual::Posicao_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_virtual::Posicao_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c80cbd8dfeeb8e79ddb6c3b83c556b03";
  }

  static const char* value(const ::robo_virtual::Posicao_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc80cbd8dfeeb8e79ULL;
  static const uint64_t static_value2 = 0xddb6c3b83c556b03ULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_virtual::Posicao_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_virtual/Posicao";
  }

  static const char* value(const ::robo_virtual::Posicao_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_virtual::Posicao_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
float32 velocidade\n\
";
  }

  static const char* value(const ::robo_virtual::Posicao_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_virtual::Posicao_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.velocidade);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Posicao_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_virtual::Posicao_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_virtual::Posicao_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "velocidade: ";
    Printer<float>::stream(s, indent + "  ", v.velocidade);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_VIRTUAL_MESSAGE_POSICAO_H
