# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raspberry_msgs/ParamAcc.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ParamAcc(genpy.Message):
  _md5sum = "f07ef5807ccc316d34a8d12ba22eff32"
  _type = "raspberry_msgs/ParamAcc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 bx
float64 by
float64 bz
float64 sx
float64 sy
float64 sz"""
  __slots__ = ['bx','by','bz','sx','sy','sz']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bx,by,bz,sx,sy,sz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ParamAcc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bx is None:
        self.bx = 0.
      if self.by is None:
        self.by = 0.
      if self.bz is None:
        self.bz = 0.
      if self.sx is None:
        self.sx = 0.
      if self.sy is None:
        self.sy = 0.
      if self.sz is None:
        self.sz = 0.
    else:
      self.bx = 0.
      self.by = 0.
      self.bz = 0.
      self.sx = 0.
      self.sy = 0.
      self.sz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.bx, _x.by, _x.bz, _x.sx, _x.sy, _x.sz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.bx, _x.by, _x.bz, _x.sx, _x.sy, _x.sz,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.bx, _x.by, _x.bz, _x.sx, _x.sy, _x.sz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.bx, _x.by, _x.bz, _x.sx, _x.sy, _x.sz,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
